[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "1.0.0-rc.1"
edition = "2021"

[workspace.dependencies]
libtor = { path = "crates/libtor" }
libtor-derive = { path = "crates/libtor-derive" }
libtor-sys = { path = "crates/libtor-sys" }
logger = { path = "crates/logger" }
tor = { path = "crates/tor" }
utils = { path = "crates/utils" }

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "unwind"
