// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "cxx.h"
#include "ffi.rs.h"
#include <react/bridging/Bridging.h>
#include <variant>
#include <iterator>
#include <algorithm>

using namespace facebook;

namespace reactnativenitrotor {

class RustVecBuffer : public jsi::MutableBuffer {
public:
  explicit RustVecBuffer(rust::Vec<uint8_t> vec)
    : vec_(std::move(vec)) {}

  ~RustVecBuffer() override = default;

  size_t size() const override {
    return vec_.size();
  }

  uint8_t* data() override {
    return const_cast<uint8_t*>(vec_.data());
  }

private:
  rust::Vec<uint8_t> vec_;
};

} // namespace reactnativenitrotor

namespace facebook {
namespace react {

template <>
struct Bridging<std::monostate> {
  static std::monostate fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    return std::monostate{};
  }

  static jsi::Value toJs(jsi::Runtime& rt, const std::monostate& value) {
    return jsi::Value::undefined();
  }
};

template <>
struct Bridging<rust::Str> {
  static rust::Str fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::Str(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Str& value) {
    return jsi::String::createFromUtf8(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::String> {
  static rust::String fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::String(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::String& value) {
    return jsi::String::createFromUtf8(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::Vec<uint8_t>> {
  static rust::Vec<uint8_t> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arrayBuffer = value.asObject(rt).getArrayBuffer(rt);
    uint8_t* data = arrayBuffer.data(rt);
    size_t size = arrayBuffer.size(rt);
    rust::Vec<uint8_t> vec;
    vec.reserve(size);

    std::copy(data, data + size, std::back_inserter(vec));

    return vec;
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Vec<uint8_t>& vec) {
    auto buffer = std::make_shared<reactnativenitrotor::RustVecBuffer>(std::move(vec));
    return jsi::ArrayBuffer(rt, buffer);
  }
};

template <typename T>
struct Bridging<rust::Vec<T>> {
  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> vec;
    vec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto element = arr.getValueAtIndex(rt, i);
      vec.push_back(react::bridging::fromJs<T>(rt, element, callInvoker));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto jsElement = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, jsElement);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::reactnativenitrotor::bridging::NativeHiddenService> {
  static craby::reactnativenitrotor::bridging::NativeHiddenService fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$onionAddress = obj.getProperty(rt, "onion_address");
    auto obj$privateKey = obj.getProperty(rt, "private_key");

    auto _obj$onionAddress = react::bridging::fromJs<rust::String>(rt, obj$onionAddress, callInvoker);
    auto _obj$privateKey = react::bridging::fromJs<rust::Vec<uint8_t>>(rt, obj$privateKey, callInvoker);

    craby::reactnativenitrotor::bridging::NativeHiddenService ret = {
      _obj$onionAddress,
      _obj$privateKey
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, const craby::reactnativenitrotor::bridging::NativeHiddenService& value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$onionAddress = react::bridging::toJs(rt, value.onion_address);
    auto _obj$privateKey = react::bridging::toJs(rt, value.private_key);

    obj.setProperty(rt, "onion_address", _obj$onionAddress);
    obj.setProperty(rt, "private_key", _obj$privateKey);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::reactnativenitrotor::bridging::NativeHiddenServiceOptions> {
  static craby::reactnativenitrotor::bridging::NativeHiddenServiceOptions fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$virtualPort = obj.getProperty(rt, "virtual_port");
    auto obj$targetPort = obj.getProperty(rt, "target_port");
    auto obj$privateKey = obj.getProperty(rt, "private_key");

    auto _obj$virtualPort = react::bridging::fromJs<double>(rt, obj$virtualPort, callInvoker);
    auto _obj$targetPort = react::bridging::fromJs<double>(rt, obj$targetPort, callInvoker);
    auto _obj$privateKey = react::bridging::fromJs<rust::Vec<uint8_t>>(rt, obj$privateKey, callInvoker);

    craby::reactnativenitrotor::bridging::NativeHiddenServiceOptions ret = {
      _obj$virtualPort,
      _obj$targetPort,
      _obj$privateKey
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, const craby::reactnativenitrotor::bridging::NativeHiddenServiceOptions& value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$virtualPort = react::bridging::toJs(rt, value.virtual_port);
    auto _obj$targetPort = react::bridging::toJs(rt, value.target_port);
    auto _obj$privateKey = react::bridging::toJs(rt, value.private_key);

    obj.setProperty(rt, "virtual_port", _obj$virtualPort);
    obj.setProperty(rt, "target_port", _obj$targetPort);
    obj.setProperty(rt, "private_key", _obj$privateKey);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::reactnativenitrotor::bridging::NativeHttpRequest> {
  static craby::reactnativenitrotor::bridging::NativeHttpRequest fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$url = obj.getProperty(rt, "url");
    auto obj$method = obj.getProperty(rt, "method");
    auto obj$headersJson = obj.getProperty(rt, "headers_json");
    auto obj$body = obj.getProperty(rt, "body");
    auto obj$timeoutMs = obj.getProperty(rt, "timeout_ms");
    auto obj$allowInvalidCertificates = obj.getProperty(rt, "allow_invalid_certificates");

    auto _obj$url = react::bridging::fromJs<rust::String>(rt, obj$url, callInvoker);
    auto _obj$method = react::bridging::fromJs<rust::String>(rt, obj$method, callInvoker);
    auto _obj$headersJson = react::bridging::fromJs<rust::String>(rt, obj$headersJson, callInvoker);
    auto _obj$body = react::bridging::fromJs<rust::String>(rt, obj$body, callInvoker);
    auto _obj$timeoutMs = react::bridging::fromJs<double>(rt, obj$timeoutMs, callInvoker);
    auto _obj$allowInvalidCertificates = react::bridging::fromJs<bool>(rt, obj$allowInvalidCertificates, callInvoker);

    craby::reactnativenitrotor::bridging::NativeHttpRequest ret = {
      _obj$url,
      _obj$method,
      _obj$headersJson,
      _obj$body,
      _obj$timeoutMs,
      _obj$allowInvalidCertificates
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, const craby::reactnativenitrotor::bridging::NativeHttpRequest& value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$url = react::bridging::toJs(rt, value.url);
    auto _obj$method = react::bridging::toJs(rt, value.method);
    auto _obj$headersJson = react::bridging::toJs(rt, value.headers_json);
    auto _obj$body = react::bridging::toJs(rt, value.body);
    auto _obj$timeoutMs = react::bridging::toJs(rt, value.timeout_ms);
    auto _obj$allowInvalidCertificates = react::bridging::toJs(rt, value.allow_invalid_certificates);

    obj.setProperty(rt, "url", _obj$url);
    obj.setProperty(rt, "method", _obj$method);
    obj.setProperty(rt, "headers_json", _obj$headersJson);
    obj.setProperty(rt, "body", _obj$body);
    obj.setProperty(rt, "timeout_ms", _obj$timeoutMs);
    obj.setProperty(rt, "allow_invalid_certificates", _obj$allowInvalidCertificates);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::reactnativenitrotor::bridging::NativeTorConfig> {
  static craby::reactnativenitrotor::bridging::NativeTorConfig fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$dataDirectory = obj.getProperty(rt, "data_directory");
    auto obj$socksPort = obj.getProperty(rt, "socks_port");
    auto obj$bootstrapTimeoutMs = obj.getProperty(rt, "bootstrap_timeout_ms");

    auto _obj$dataDirectory = react::bridging::fromJs<rust::String>(rt, obj$dataDirectory, callInvoker);
    auto _obj$socksPort = react::bridging::fromJs<double>(rt, obj$socksPort, callInvoker);
    auto _obj$bootstrapTimeoutMs = react::bridging::fromJs<double>(rt, obj$bootstrapTimeoutMs, callInvoker);

    craby::reactnativenitrotor::bridging::NativeTorConfig ret = {
      _obj$dataDirectory,
      _obj$socksPort,
      _obj$bootstrapTimeoutMs
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, const craby::reactnativenitrotor::bridging::NativeTorConfig& value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$dataDirectory = react::bridging::toJs(rt, value.data_directory);
    auto _obj$socksPort = react::bridging::toJs(rt, value.socks_port);
    auto _obj$bootstrapTimeoutMs = react::bridging::toJs(rt, value.bootstrap_timeout_ms);

    obj.setProperty(rt, "data_directory", _obj$dataDirectory);
    obj.setProperty(rt, "socks_port", _obj$socksPort);
    obj.setProperty(rt, "bootstrap_timeout_ms", _obj$bootstrapTimeoutMs);

    return jsi::Value(rt, obj);
  }
};

} // namespace react
} // namespace facebook
