// Auto generated by Craby. DO NOT EDIT.
#include "CxxReactNativeNitroTorModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace reactnativenitrotor {
namespace modules {

std::string CxxReactNativeNitroTorModule::dataPath = std::string();

CxxReactNativeNitroTorModule::CxxReactNativeNitroTorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxReactNativeNitroTorModule::kModuleName, jsInvoker) {
  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& manager = craby::reactnativenitrotor::signals::SignalManager::getInstance();
  manager.registerDelegate(id,
    [this](const std::string& name, void* signal) {
      this->emit(name, reinterpret_cast<bridging::ReactNativeNitroTorSignal*>(signal));
    }
  );
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::reactnativenitrotor::bridging::ReactNativeNitroTor>(
    craby::reactnativenitrotor::bridging::createReactNativeNitroTor(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::reactnativenitrotor::bridging::ReactNativeNitroTor *ptr) { rust::Box<craby::reactnativenitrotor::bridging::ReactNativeNitroTor>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::reactnativenitrotor::utils::ThreadPool>(10);
  methodMap_["createHiddenService"] = MethodMetadata{1, &CxxReactNativeNitroTorModule::createHiddenService};
  methodMap_["getStatus"] = MethodMetadata{0, &CxxReactNativeNitroTorModule::getStatus};
  methodMap_["httpRequest"] = MethodMetadata{1, &CxxReactNativeNitroTorModule::httpRequest};
  methodMap_["removeHiddenService"] = MethodMetadata{1, &CxxReactNativeNitroTorModule::removeHiddenService};
  methodMap_["requestNewIdentity"] = MethodMetadata{0, &CxxReactNativeNitroTorModule::requestNewIdentity};
  methodMap_["start"] = MethodMetadata{1, &CxxReactNativeNitroTorModule::start};
  methodMap_["stop"] = MethodMetadata{0, &CxxReactNativeNitroTorModule::stop};
  methodMap_["onStatusChange"] = MethodMetadata{1, &CxxReactNativeNitroTorModule::onStatusChange};
}

CxxReactNativeNitroTorModule::~CxxReactNativeNitroTorModule() {
  invalidate();
}

void CxxReactNativeNitroTorModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  {
    std::lock_guard<std::mutex> lock(listenersMutex_);
    listenersMap_.clear();
  }

  // Unregister from signal manager
  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& manager = craby::reactnativenitrotor::signals::SignalManager::getInstance();
  manager.unregisterDelegate(id);

  // Shutdown thread pool
  threadPool_->shutdown();
}

void CxxReactNativeNitroTorModule::emit(std::string name, bridging::ReactNativeNitroTorSignal* signal) {
  std::vector<std::shared_ptr<facebook::jsi::Function>> listeners;
  {
    std::lock_guard<std::mutex> lock(listenersMutex_);
    auto it = listenersMap_.find(name);
    if (it != listenersMap_.end()) {
      for (auto &[_, listener] : it->second) {
        listeners.push_back(listener);
      }
    }
  }

  // Prepare payload: extract from signal or use undefined
  auto payloadPtr = std::make_shared<facebook::jsi::Value>();

  if (signal == nullptr) {
    *payloadPtr = facebook::jsi::Value::undefined();
  } else {
    // Use shared_ptr to manage signal lifetime across async callbacks
    auto signalPtr = std::shared_ptr<bridging::ReactNativeNitroTorSignal>(
      signal,
      [](bridging::ReactNativeNitroTorSignal* ptr) {
        // Use Rust FFI function to drop signal memory
        if (ptr != nullptr) {
          craby::reactnativenitrotor::bridging::drop_signal(ptr);
        }
      }
    );

    // Extract payload using FFI function and convert to jsi::Value
    // We'll need to capture signalPtr in the lambda
    for (auto& listener : listeners) {
      try {
        callInvoker_->invokeAsync([listener, signalPtr, name](jsi::Runtime &rt) {
          jsi::Value data = jsi::Value::undefined();
          if (name == "onStatusChange") {
            auto payload = craby::reactnativenitrotor::bridging::get_on_status_change_payload(*signalPtr);
            data = react::bridging::toJs(rt, payload);
          }
          listener->call(rt, data);
        });
      } catch (const std::exception& err) {
        // Noop
      }
    }
    return;
  }

  for (auto& listener : listeners) {
    try {
      callInvoker_->invokeAsync([listener, payloadPtr](jsi::Runtime &rt) {
        try {
          listener->call(rt, *payloadPtr);
        } catch (const jsi::JSError &err) {
          throw err;
        } catch (const std::exception &err) {
          throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
        }
      });
    } catch (const std::exception& err) {
      // Noop
    }
  }
}

jsi::Value CxxReactNativeNitroTorModule::createHiddenService(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<craby::reactnativenitrotor::bridging::NativeHiddenServiceOptions>(rt, args[0], callInvoker);
    react::AsyncPromise<craby::reactnativenitrotor::bridging::NativeHiddenService> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0]() mutable {
      try {
        auto ret = craby::reactnativenitrotor::bridging::createHiddenService(*it_, arg0);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::getStatus(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    react::AsyncPromise<rust::String> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise]() mutable {
      try {
        auto ret = craby::reactnativenitrotor::bridging::getStatus(*it_);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::httpRequest(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<craby::reactnativenitrotor::bridging::NativeHttpRequest>(rt, args[0], callInvoker);
    react::AsyncPromise<rust::String> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0]() mutable {
      try {
        auto ret = craby::reactnativenitrotor::bridging::httpRequest(*it_, arg0);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::removeHiddenService(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0$raw]() mutable {
      try {
        auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
        craby::reactnativenitrotor::bridging::removeHiddenService(*it_, arg0);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::requestNewIdentity(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise]() mutable {
      try {
        craby::reactnativenitrotor::bridging::requestNewIdentity(*it_);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::start(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<craby::reactnativenitrotor::bridging::NativeTorConfig>(rt, args[0], callInvoker);
    react::AsyncPromise<rust::String> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0]() mutable {
      try {
        auto ret = craby::reactnativenitrotor::bridging::start(*it_, arg0);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::stop(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise]() mutable {
      try {
        craby::reactnativenitrotor::bridging::stop(*it_);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::reactnativenitrotor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

jsi::Value CxxReactNativeNitroTorModule::onStatusChange(jsi::Runtime &rt,
                      react::TurboModule &turboModule,
                      const jsi::Value args[],
                      size_t count) {
  auto &thisModule = static_cast<CxxReactNativeNitroTorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto callback = args[0].asObject(rt).asFunction(rt);
    auto callbackRef = std::make_shared<jsi::Function>(std::move(callback));
    auto id = thisModule.nextListenerId_.fetch_add(1);
    auto name = "onStatusChange";

    {
      std::lock_guard<std::mutex> lock(thisModule.listenersMutex_);
      thisModule.listenersMap_[name].emplace(id, callbackRef);
    }

    auto modulePtr = &thisModule;
    auto cleanup = [modulePtr, name, id] {
      std::lock_guard<std::mutex> lock(modulePtr->listenersMutex_);
      auto eventMap = modulePtr->listenersMap_.find(name);
      if (eventMap != modulePtr->listenersMap_.end()) {
        auto it = eventMap->second.find(id);
        if (it != eventMap->second.end()) {
          eventMap->second.erase(it);
        }
      }
      return jsi::Value::undefined();
    };

    return jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "cleanup"),
      0,
      [cleanup](jsi::Runtime& rt, const jsi::Value&, const jsi::Value*, size_t) -> jsi::Value {
        return cleanup();
      }
    );
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::reactnativenitrotor::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace reactnativenitrotor
} // namespace craby
