// Auto generated by Craby. DO NOT EDIT.
#include "CxxReactNativeNitroTorModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace reactnativenitrotor {
namespace modules {

std::string CxxReactNativeNitroTorModule::dataPath = std::string();

CxxReactNativeNitroTorModule::CxxReactNativeNitroTorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxReactNativeNitroTorModule::kModuleName, jsInvoker) {
}

CxxReactNativeNitroTorModule::~CxxReactNativeNitroTorModule() {
}

} // namespace modules
} // namespace reactnativenitrotor
} // namespace craby
