// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <memory>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

namespace craby {
namespace reactnativenitrotor {
namespace modules {

class JSI_EXPORT CxxReactNativeNitroTorModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "ReactNativeNitroTor";

  CxxReactNativeNitroTorModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxReactNativeNitroTorModule();

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
};

} // namespace modules
} // namespace reactnativenitrotor
} // namespace craby
