// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "CrabyUtils.hpp"
#include "ffi.rs.h"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace reactnativenitrotor {
namespace modules {

class JSI_EXPORT CxxReactNativeNitroTorModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "ReactNativeNitroTor";
  static std::string dataPath;

  CxxReactNativeNitroTorModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxReactNativeNitroTorModule();

  void invalidate();
  void emit(std::string name, bridging::ReactNativeNitroTorSignal* signal);

  static facebook::jsi::Value
  createHiddenService(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  getStatus(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  httpRequest(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  removeHiddenService(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  requestNewIdentity(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  start(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  stop(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  onStatusChange(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::reactnativenitrotor::bridging::ReactNativeNitroTor> module_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
  std::shared_ptr<craby::reactnativenitrotor::utils::ThreadPool> threadPool_;
  std::shared_ptr<craby::reactnativenitrotor::utils::ThreadPool> lifecycleThreadPool_;
};

} // namespace modules
} // namespace reactnativenitrotor
} // namespace craby
