// Auto generated by Craby. DO NOT EDIT.
#import "CxxReactNativeNitroTorModule.hpp"

#import <ReactCommon/CxxTurboModuleUtils.h>

@interface ReactNativeNitroTorModuleProvider : NSObject
@end

@implementation ReactNativeNitroTorModuleProvider
+ (void)load {
}
@end
