// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::react_native_nitro_tor_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::reactnativenitrotor::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct NativeHttpRequest {
        url: String,
        method: String,
        headers_json: String,
        body: String,
        timeout_ms: f64,
        allow_invalid_certificates: bool,
    }

    #[derive(Clone)]
    struct NativeTorConfig {
        data_directory: String,
        socks_port: f64,
        bootstrap_timeout_ms: f64,
    }

    #[derive(Clone)]
    struct NativeHiddenServiceOptions {
        virtual_port: f64,
        target_port: f64,
        private_key: Vec<u8>,
    }

    #[derive(Clone)]
    struct NativeHiddenService {
        onion_address: String,
        private_key: Vec<u8>,
    }

    extern "Rust" {
        type ReactNativeNitroTor;

        #[cxx_name = "createReactNativeNitroTor"]
        fn create_react_native_nitro_tor(id: usize, data_path: &str) -> Box<ReactNativeNitroTor>;

        #[cxx_name = "createHiddenService"]
        fn react_native_nitro_tor_create_hidden_service(it_: &ReactNativeNitroTor, options: NativeHiddenServiceOptions) -> Result<NativeHiddenService>;

        #[cxx_name = "getStatus"]
        fn react_native_nitro_tor_get_status(it_: &ReactNativeNitroTor) -> Result<String>;

        #[cxx_name = "httpRequest"]
        fn react_native_nitro_tor_http_request(it_: &ReactNativeNitroTor, request: NativeHttpRequest) -> Result<String>;

        #[cxx_name = "removeHiddenService"]
        fn react_native_nitro_tor_remove_hidden_service(it_: &ReactNativeNitroTor, onion_address: &str) -> Result<()>;

        #[cxx_name = "requestNewIdentity"]
        fn react_native_nitro_tor_request_new_identity(it_: &ReactNativeNitroTor) -> Result<()>;

        #[cxx_name = "start"]
        fn react_native_nitro_tor_start(it_: &ReactNativeNitroTor, config: NativeTorConfig) -> Result<String>;

        #[cxx_name = "stop"]
        fn react_native_nitro_tor_stop(it_: &ReactNativeNitroTor) -> Result<()>;
    }

    extern "Rust" {
        type ReactNativeNitroTorSignal;
        fn get_on_status_change_payload(s: &ReactNativeNitroTorSignal) -> String;
        unsafe fn drop_signal(signal: *mut ReactNativeNitroTorSignal);
    }

    #[namespace = "craby::reactnativenitrotor::signals"]
    unsafe extern "C++" {
        include!("CrabySignals.h");

        type SignalManager;

        unsafe fn emit(self: &SignalManager, id: usize, name: &str, signal: *mut ReactNativeNitroTorSignal) -> bool;

        #[rust_name = "get_signal_manager"]
        fn getSignalManager() -> &'static SignalManager;
    }
}

fn create_react_native_nitro_tor(id: usize, data_path: &str) -> Box<ReactNativeNitroTor> {
    let ctx = Context::new(id, data_path);
    Box::new(ReactNativeNitroTor::new(ctx))
}

fn react_native_nitro_tor_create_hidden_service(it_: &ReactNativeNitroTor, options: NativeHiddenServiceOptions) -> Result<NativeHiddenService, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.create_hidden_service(options);
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_get_status(it_: &ReactNativeNitroTor) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get_status();
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_http_request(it_: &ReactNativeNitroTor, request: NativeHttpRequest) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.http_request(request);
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_remove_hidden_service(it_: &ReactNativeNitroTor, onion_address: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.remove_hidden_service(onion_address);
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_request_new_identity(it_: &ReactNativeNitroTor) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.request_new_identity();
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_start(it_: &ReactNativeNitroTor, config: NativeTorConfig) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.start(config);
        ret
    }).and_then(|r| r)
}

fn react_native_nitro_tor_stop(it_: &ReactNativeNitroTor) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.stop();
        ret
    }).and_then(|r| r)
}

fn get_on_status_change_payload(s: &ReactNativeNitroTorSignal) -> String {
    match s {
        ReactNativeNitroTorSignal::OnStatusChange(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_on_status_change_payload"),
    }
}

unsafe fn drop_signal(signal: *mut ReactNativeNitroTorSignal) {
    if !signal.is_null() {
        drop(Box::from_raw(signal));
    }
}
