// Auto generated by Craby. DO NOT EDIT.
// Hash: a8b84e3d6271341b
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ReactNativeNitroTorSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn emit(&self, signal_name: ReactNativeNitroTorSignal) {
        let manager = crate::ffi::bridging::get_signal_manager();
        match signal_name {
            ReactNativeNitroTorSignal::OnStatusChange(data) => {
                let signal = Box::new(ReactNativeNitroTorSignal::OnStatusChange(data));
                let signal_ptr = Box::into_raw(signal);
                let delivered = unsafe { manager.emit(self.id(), "onStatusChange", signal_ptr) };
                if !delivered {
                    unsafe {
                        drop(Box::from_raw(signal_ptr));
                    }
                }
            }
        }
    }
    fn create_hidden_service(
        &self,
        options: NativeHiddenServiceOptions,
    ) -> Promise<NativeHiddenService>;
    fn get_status(&self) -> Promise<String>;
    fn http_request(&self, request: NativeHttpRequest) -> Promise<String>;
    fn remove_hidden_service(&self, onion_address: &str) -> Promise<Void>;
    fn request_new_identity(&self) -> Promise<Void>;
    fn start(&self, config: NativeTorConfig) -> Promise<String>;
    fn stop(&self) -> Promise<Void>;
}

pub enum ReactNativeNitroTorSignal {
    OnStatusChange(String),
}

impl Default for NativeHiddenService {
    fn default() -> Self {
        NativeHiddenService {
            onion_address: String::default(),
            private_key: Vec::default(),
        }
    }
}

impl Default for NativeHttpRequest {
    fn default() -> Self {
        NativeHttpRequest {
            url: String::default(),
            method: String::default(),
            headers_json: String::default(),
            body: String::default(),
            timeout_ms: 0.0,
            allow_invalid_certificates: false,
        }
    }
}

impl Default for NativeHiddenServiceOptions {
    fn default() -> Self {
        NativeHiddenServiceOptions {
            virtual_port: 0.0,
            target_port: 0.0,
            private_key: Vec::default(),
        }
    }
}

impl Default for NativeTorConfig {
    fn default() -> Self {
        NativeTorConfig {
            data_directory: String::default(),
            socks_port: 0.0,
            bootstrap_timeout_ms: 0.0,
        }
    }
}
