// Auto generated by Craby. DO NOT EDIT.
// Hash: 90d5605f4a1dbf8c
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ReactNativeNitroTorSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn create_hidden_service(&mut self, params: HiddenServiceParams) -> Promise<HiddenServiceResponse>;
    fn delete_hidden_service(&mut self, onion_address: &str) -> Promise<Boolean>;
    fn get_service_status(&mut self) -> Promise<Number>;
    fn http_delete(&mut self, params: HttpDeleteParams) -> Promise<HttpResponse>;
    fn http_get(&mut self, params: HttpGetParams) -> Promise<HttpResponse>;
    fn http_post(&mut self, params: HttpPostParams) -> Promise<HttpResponse>;
    fn http_put(&mut self, params: HttpPutParams) -> Promise<HttpResponse>;
    fn init_tor_service(&mut self, config: TorConfig) -> Promise<Boolean>;
    fn shutdown_service(&mut self) -> Promise<Boolean>;
    fn start_tor_if_not_running(&mut self, params: StartTorParams) -> Promise<StartTorResponse>;
}

impl Default for HiddenServiceResponse {
    fn default() -> Self {
        HiddenServiceResponse {
            is_success: false,
            onion_address: String::default(),
            control: String::default()
        }
    }
}

impl Default for StartTorResponse {
    fn default() -> Self {
        StartTorResponse {
            is_success: false,
            onion_address: String::default(),
            control: String::default(),
            error_message: String::default()
        }
    }
}

impl Default for HttpDeleteParams {
    fn default() -> Self {
        HttpDeleteParams {
            url: String::default(),
            headers: String::default(),
            timeout_ms: 0.0
        }
    }
}

impl Default for HttpPostParams {
    fn default() -> Self {
        HttpPostParams {
            url: String::default(),
            body: String::default(),
            headers: String::default(),
            timeout_ms: 0.0
        }
    }
}

impl Default for TorConfig {
    fn default() -> Self {
        TorConfig {
            socks_port: 0.0,
            data_dir: String::default(),
            timeout_ms: 0.0
        }
    }
}

impl Default for HiddenServiceParams {
    fn default() -> Self {
        HiddenServiceParams {
            port: 0.0,
            target_port: 0.0
        }
    }
}

impl Default for HttpGetParams {
    fn default() -> Self {
        HttpGetParams {
            url: String::default(),
            headers: String::default(),
            timeout_ms: 0.0
        }
    }
}

impl Default for StartTorParams {
    fn default() -> Self {
        StartTorParams {
            data_dir: String::default(),
            socks_port: 0.0,
            target_port: 0.0,
            timeout_ms: 0.0
        }
    }
}

impl Default for HttpPutParams {
    fn default() -> Self {
        HttpPutParams {
            url: String::default(),
            body: String::default(),
            headers: String::default(),
            timeout_ms: 0.0
        }
    }
}

impl Default for HttpResponse {
    fn default() -> Self {
        HttpResponse {
            status_code: 0.0,
            body: String::default(),
            error: String::default()
        }
    }
}
